version: "3.8"
services:
  specs:
    build:
      context: .
      # https://github.com/docker/compose/issues/7397
      dockerfile: ../../research/syntax/template/docker/Dockerfile
    env_file:
      - input.env
