# checks:
#   javascript:
#     no_var: true
#     no_param_assign: true
#     no_loop_var_assign: true
#     no_implicit_undefined_return: true
#     no_else_return: true
#     no_alert: true
#     eqeqeq: true
build:
  environment:
    node: 14.16.0
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    tests: true
    # coverage:
    #   tests:
    #     override:
    #       - command: npm run test
    #         coverage:
    #           file: coverage/clover.xml
    #           format: clover
filter:
  excluded_paths:
  - "**/node_modules/"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/*.d.ts"
  - "__e2e__/"
  - "research/"
