export { }
/** docker-compose config */
const environmentYml = {
  DOCKER_OVERRIDE_INLINE: "environment",
  DOCKER_OVERRIDE_INTERNAL_1: "docker/.env.file1",
  DOCKER_OVERRIDE_INTERNAL_2: "docker/.env.file2",
  ENV_INLINE: "environment",
  ENV_INTERNAL1: "docker/.env.file1",
  ENV_INTERNAL2: "docker/.env.file2",
  ENV_ROOT: ".env",
  EXPORT_OVERRIDE_INLINE: "environment",
  EXPORT_OVERRIDE_INTERNAL_1: "docker/.env.file1",
  EXPORT_OVERRIDE_INTERNAL_2: "docker/.env.file2",
  EXPORT_OVERRIDE_ROOT: ".env",
  INLINE_CATCH_DOCKER: null,
  INLINE_CATCH_EXPORT: null,
  INLINE_CATCH_INTERNAL_1: null,
  INLINE_CATCH_INTERNAL_2: null,
  INLINE_CATCH_ROOT: ".env",
  INLINE_CATCH_RUN: null,
  INLINE_OVERRIDE_INTERNAL_1: "environment",
  INLINE_OVERRIDE_INTERNAL_2: "environment",
  INLINE_OVERRIDE_ROOT: "environment",
  INLINE_OVERRIDE_RUN: "environment",
  INTERNAL_1_CATCH_DOCKER: null,
  INTERNAL_1_CATCH_EXPORT: null,
  INTERNAL_1_CATCH_INLINE: null,
  INTERNAL_1_CATCH_INTERNAL_2: null,
  INTERNAL_1_CATCH_ROOT: null,
  INTERNAL_1_CATCH_RUN: null,
  INTERNAL_1_OVERRIDE_INTERNAL_2: "docker/.env.file2",
  INTERNAL_1_OVERRIDE_ROOT: "docker/.env.file1",
  INTERNAL_1_OVERRIDE_RUN: "docker/.env.file1",
  INTERNAL_2_CATCH_DOCKER: null,
  INTERNAL_2_CATCH_EXPORT: null,
  INTERNAL_2_CATCH_INLINE: null,
  INTERNAL_2_CATCH_INTERNAL_1: null,
  INTERNAL_2_CATCH_ROOT: null,
  INTERNAL_2_CATCH_RUN: null,
  INTERNAL_2_OVERRIDE_ROOT: "docker/.env.file2",
  INTERNAL_2_OVERRIDE_RUN: "docker/.env.file2",
  ROOT_CATCH_EXPORT: null
}
