version: "3.8"
services: 
  env_file:
    env_file:
      # - ../docker-compose/.env - no changes
      - ../docker/.env
    build:
      context: ../docker
      dockerfile: Dockerfile
  env_injected:
    # env_file:
      # - ../docker-compose/.env - no changes
      # - ../docker/.env - breaks
    build:
      context: ../docker
      dockerfile: Dockerfile.injected
  injected:
    build:
      context: ../docker
      dockerfile: Dockerfile
    environment: 
      - FROM_GLOBAL1=$GLOBAL
      - FROM_GLOBAL2=${GLOBAL}
      - FROM_GLOBAL3="$GLOBAL"
      - FROM_GLOBAL4="${GLOBAL}"
      - STR_DIRECT=direct
      - STR_SINGLE='single'
      - STR_DOUBLE="double"
      - STR_BACKTICK=`backtick`
      - STR_EMPTY=
      - VAR="var"
      - VAR1="var1"
      - DOUBLE_DOLLAR=$$VAR1
      - VAR_DIRECT=$VAR1
      - VAR_SINGLE='$VAR1'
      - VAR_DOUBLE="$VAR1"
      - VAR_CURVE=${VAR1}
      - VAR_CURVE_SINGLE='${VAR1}'
      - VAR_CURVE_DOUBLE="${VAR1}"
      - VAR_REPEAT=$VAR1$VAR1
      - VAR_DEFAULT1=${XXX:-$VAR1}
      - VAR_DEFAULT2=${STR_EMPTY:-$VAR1}
      # - VAR_DEFAULT3=${XXX:$VAR1}
      # - VAR_DEFAULT4=${STR_EMPTY:$VAR1}
      - VAR_DEFAULT_DEFAULT=${XXX:-${YYY:-VAR1}}
      # - VAR_SHOULD1=${VAR1?err1}
      # - VAR_SHOULD2=${VAR1?:err1}
      # - VAR_SHOULD3=${STR_EMPTY?err2} 
      # - VAR_SHOULD4=${STR_EMPTY?:err2} 
