version: "3.8"
services:
  envs_propagation:
    build:
      context: ./docker
    env_file:
      - ./docker/.env.file1
      - ./docker/.env.file2
    environment:
      # from root
      - ENV_ROOT
      - ROOT_CATCH_DOCKER
      - ROOT_CATCH_EXPORT
      - ROOT_CATCH_INLINE
      - ROOT_CATCH_INTERNAL_1
      - ROOT_CATCH_INTERNAL_2
      - ROOT_CATCH_RUN
      - DOCKER_OVERRIDE_ROOT
      - EXPORT_OVERRIDE_ROOT
      - INTERNAL_1_OVERRIDE_ROOT
      - INTERNAL_2_OVERRIDE_ROOT
      - ROOT_OVERRIDE_RUN

      - INLINE_CATCH_ROOT_2=${ENV_ROOT_2}  #NB
      - INLINE_CATCH_EXPORT_2=${ENV_EXPORT_2} #NB

      - ENV_INLINE="environment"

      - INLINE_CATCH_DOCKER=${ENV_DOCKER}
      - INLINE_CATCH_EXPORT=${ENV_EXPORT}

      - INLINE_CATCH_INTERNAL_1=${ENV_INTERNAL_1}
      - INLINE_CATCH_INTERNAL_2=${ENV_INTERNAL_2}
      - INLINE_CATCH_ROOT=${ENV_ROOT}
      - INLINE_CATCH_RUN=${ENV_RUN}

      - DOCKER_OVERRIDE_INLINE="environment"
      - EXPORT_OVERRIDE_INLINE="environment"

      - INLINE_OVERRIDE_INTERNAL_1="environment"
      - INLINE_OVERRIDE_INTERNAL_2="environment"
      - INLINE_OVERRIDE_ROOT="environment"
      - INLINE_OVERRIDE_RUN="environment"
