version: "3.8"
services:
  envs_propagation:
    build:
      context: ./docker
    env_file:
      - ./docker/.env.file1
      - ./docker/.env.file2
    environment:
      - ENV_ROOT
      - ROOT_CATCH_EXPORT
      - EXPORT_OVERRIDE_ROOT

      - ENV_INLINE="environment"

      - INLINE_CATCH_DOCKER=${ENV_DOCKER}
      - INLINE_CATCH_EXPORT=${ENV_EXPORT}

      - INLINE_CATCH_INTERNAL_1=${ENV_INTERNAL_1}
      - INLINE_CATCH_INTERNAL_2=${ENV_INTERNAL_2}
      - INLINE_CATCH_ROOT=${ENV_ROOT}
      - INLINE_CATCH_RUN=${ENV_RUN}

      - DOCKER_OVERRIDE_INLINE="environment"
      - EXPORT_OVERRIDE_INLINE="environment"

      - INLINE_OVERRIDE_INTERNAL_1="environment"
      - INLINE_OVERRIDE_INTERNAL_2="environment"
      - INLINE_OVERRIDE_ROOT="environment"
      - INLINE_OVERRIDE_RUN="environment"
