version: "3.8"
services:
  envs_propagation:
    build:
      context: ./docker
    env_file:
      - ./docker/.env.file1
      - ./docker/.env.file2
    environment:
      - ENV_ROOT_1
      - ROOT_CATCH_EXPORT
      - EXPORT_OVERRIDE_ROOT

      - INLINE="environment"

      - INLINE_CATCH_INTERNAL_0=${ENV_INTERNAL_0}
      - INLINE_CATCH_INTERNAL_1=${ENV_INTERNAL_1}
      - INLINE_CATCH_ROOT2=${ENV_ROOT_2}
      - INLINE_CATCH_EXPORT=${ENV_EXPORT}

      - EXPORT_OVERRIDE_INLINE=environment
      - ROOT_OVERRIDE_INLINE=environment

      - INLINE_OVERRIDE_INTERNAL=environment
      - INLINE_OVERRIDE_DOCKER=environment
