services:
  envs_propagation:
    build:
      context: /Users/kirmasy/code/dotenv/propagation/docker
    environment:
      DOCKER_OVERRIDE_INLINE: environment
      DOCKER_OVERRIDE_INTERNAL_1: docker/.env.file1
      DOCKER_OVERRIDE_INTERNAL_2: docker/.env.file2
      DOCKER_OVERRIDE_ROOT: .env
      ENV_INLINE: environment
      ENV_INTERNAL1: docker/.env.file1
      ENV_INTERNAL2: docker/.env.file2
      ENV_ROOT: .env
      EXPORT_OVERRIDE_INLINE: environment
      EXPORT_OVERRIDE_INTERNAL_1: docker/.env.file1
      EXPORT_OVERRIDE_INTERNAL_2: docker/.env.file2
      EXPORT_OVERRIDE_ROOT: global
      INLINE_CATCH_DOCKER: ''
      INLINE_CATCH_EXPORT: global
      INLINE_CATCH_EXPORT_2: global
      INLINE_CATCH_INTERNAL_1: ''
      INLINE_CATCH_INTERNAL_2: ''
      INLINE_CATCH_ROOT: .env
      INLINE_CATCH_ROOT_2: .env
      INLINE_CATCH_RUN: run
      INLINE_OVERRIDE_INTERNAL_1: environment
      INLINE_OVERRIDE_INTERNAL_2: environment
      INLINE_OVERRIDE_ROOT: environment
      INLINE_OVERRIDE_RUN: environment
      INTERNAL_1_CATCH_DOCKER: ''
      INTERNAL_1_CATCH_EXPORT: global
      INTERNAL_1_CATCH_INLINE: ''
      INTERNAL_1_CATCH_INTERNAL_2: ''
      INTERNAL_1_CATCH_ROOT: ''
      INTERNAL_1_CATCH_RUN: run
      INTERNAL_1_OVERRIDE_INTERNAL_2: docker/.env.file2
      INTERNAL_1_OVERRIDE_ROOT: .env
      INTERNAL_1_OVERRIDE_RUN: docker/.env.file1
      INTERNAL_2_CATCH_DOCKER: ''
      INTERNAL_2_CATCH_EXPORT: global
      INTERNAL_2_CATCH_INLINE: ''
      INTERNAL_2_CATCH_INTERNAL_1: ''
      INTERNAL_2_CATCH_ROOT: ''
      INTERNAL_2_CATCH_RUN: run
      INTERNAL_2_OVERRIDE_ROOT: .env
      INTERNAL_2_OVERRIDE_RUN: docker/.env.file2
      ROOT_CATCH_DOCKER: ''
      ROOT_CATCH_EXPORT: global
      ROOT_CATCH_INLINE: ''
      ROOT_CATCH_INTERNAL_1: ''
      ROOT_CATCH_INTERNAL_2: ''
      ROOT_CATCH_RUN: run
      ROOT_OVERRIDE_RUN: .env
version: '3.8'

