version: "3.8"
services:
  environment:
    build:
      context: ../docker
      dockerfile: Dockerfile
    environment:
      ### <vars prefix=- type=environment />
  env_file-shell:
    build:
      context: ../docker
      dockerfile: Dockerfile
    env_file: ../shell.env
  env_file-docker:
    build:
      context: ../docker
      dockerfile: Dockerfile
    env_file: ../docker.env
